### ISSUE TITLE
ESM Import Fails

### ISSUE THREAD

**Issue by em-ctc** [solana-fm/explorer-kit#18]
**Describe the bug**

I've installed the package into my CommonJS typescript application, however I get the following error when attempting to import the module:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module ... /node_modules/change-case/dist/index.js
```

Can this get updated to support CommonJS? The cause appears to be the `change-case` package that only gets used once to change a string to snake case. 

This could easily be updated to use a local copy instead of relying on this module:

https://www.30secondsofcode.org/js/s/string-case-conversion/#convert-any-case-to-snake-case

**Comment by em-ctc** [comment]
PR here: https://github.com/solana-fm/explorer-kit/pull/19

**Comment by doodoo-aihc** [comment]
Hey @em-ctc, really sorry for the late responses over here. Let me get back to the PRs that you have created by the end of the week, really appreicate the help :x

**Comment by doodoo-aihc** [comment]
Fixed! Thank you very much for the help :)
